services:
  postgres_course:
    image: postgres:16
    container_name: postgres_course
    environment:
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_pass
      POSTGRES_DB: course_db
    ports:
      - "5433:5432"
    volumes:
      - pg_course_data:/var/lib/postgresql/data

  postgres_user:
    image: postgres:16
    container_name: postgres_user
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
      POSTGRES_DB: user_db
    ports:
      - "5434:5432"
    volumes:
      - pg_user_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  pg_course_data:
  pg_user_data:
  qdrant_data:
